### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [Wyorancher/colmar-academy#3]
Alternatively, you could use comma-separated selectors to specify shared properties among elements at one time:

```css
h1, h2, h3, h4 {
  font-family: Helvetica;
  font-weight: bold;
}
```

https://github.com/Wyorancher/colmar-academy/blob/master/resourses/css/style.css#L14-L36
